spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopappnew?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
#    show-sql:Kích hoạt việc hiển thị các câu lệnh SQL mà Hibernate thực thi trong log.
    show-sql: true
    hibernate:
#      ddl-auto các câu lệnh tạo bảng và cột trong java sẽ không tự động tạo bảng và cột trong csdl nữa
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#      Khi kết hợp với show-sql, cấu hình này sẽ định dạng các câu lệnh SQL trong log để dễ đọc hơn.
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30days =30* 24 * 60 * 60
  secretKey: NRa5tDl17x9Qk/Ik0U/zg8OmVBHGM97ElNUZ8L2PIB4=
